### ISSUE TITLE
Mini-map URLs retain redundant parameters

### ISSUE THREAD

**Issue by LogicalAtomist** [ui-libraries/PM-MATS#59]
From Kevin Klement:

"One minor "bug" I noticed is that when you click a circle from one number to go to another, the URL query parameter 'n=' is duplicated rather than replaced, and if you keep going you get more and more, e.g.:

When I went to 4.53 and then 24.6 and then 24.14 the URL looked like this:

[https://principia.lib.uiowa.edu/?n=24.14&n=24.6&n=4.53](https://principia.lib.uiowa.edu/?n=24.14&n=24.6&n=4.53I)

Where the second two n= parameters are probably redundant and ignored. This presumably should just be:

https://principia.lib.uiowa.edu/?n=24.14"

**Comment by mbutler** [comment]
2457783bedf3677c9242047b458bf7f6c5ffa5f0
